{{- if .Values.cert.enabled -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: envelopegame
spec:
  acme:
    email: cloudservices@liatr.io
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: envelope-game-issuer-account-key
    solvers:
    - selector:
        dnsNames:
        - envelopegame.com
        - envelope-game.aks-lz-dev.azurecaf.liatr.io
      http01:
        ingress:
          class: nginx
          ingressTemplate:
            metadata:
              annotations:
                kubernetes.io/ingress.class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envelopegame
spec:
  secretName: envelopegame-cert
  dnsNames:
  - envelopegame.com
  - envelope-game.aks-lz-dev.azurecaf.liatr.io
  privateKey:
    rotationPolicy: Always
  issuerRef:
    name: envelopegame
    kind: Issuer
{{- end }}
