{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Release.Name }}"
spec:
  hosts:
  - {{ .Values.istio.host }}
  gateways:
  - istio-system/app-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ include "envelope-game.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{ end }}
