name: Post Release

on:
  release:
    types:
      - published
  workflow_dispatch: {}

env:
  IMAGE_NAME: ghcr.io/liatrio/envelope-game
  NAMESPACE: envelope-game
  CLUSTER_RESOURCE_GROUP_NAME: ${{ secrets.CLUSTER_RESOURCE_GROUP_NAME }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

jobs:
  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}

  helm:

    needs: docker

    name: Helm Deploy Dev
    runs-on: ubuntu-latest
    environment: envelope-game-dev

    steps:
      - name: AKS Set Context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      - name: Create Namespace if !exist
        run: |
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o json | kubectl apply -f -

      - name: '⎈ Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: envelope-game
          namespace: ${{ env.NAMESPACE }}
          chart: envelope-game
          repo: https://liatrio.github.io/envelope-game
          token: '${{ github.token }}'
          values: |
            image.name: ${{ env.IMAGE_NAME }}:${{ docker.outputs.tag }}
