name: Post Release

on:
  release:
    types:
      - published
  workflow_dispatch: {}

env:
  IMAGE_NAME: ghcr.io/liatrio/envelope-game
  NAMESPACE: envelope-game
  CLUSTER_RESOURCE_GROUP_NAME: ${{ secrets.CLUSTER_RESOURCE_GROUP_NAME }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

jobs:
  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Tag
        id: tag
        run: echo "TAG=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ env.TAG }}

  helm:

    needs: docker

    name: Helm Deploy Dev
    runs-on: [self-hosted, liatrio-runners-prod]
    environment: envelope-game-dev

    steps:

      - name: Install az-cli
        run: sudo apt-get update && sudo apt-get -y install azure-cli

      - name: AZ Login
        env:
          CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          az login --service-principal -u "$CLIENT_ID" -p "$CLIENT_SECRET" --tenant "$TENANT_ID" --allow-no-subscriptions

      - name: AKS Set Context
        uses: azure/aks-set-context@v3.0
        with:
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP_NAME }}

      - name: Install Helm
        uses: azure/setup-helm@v2.1
        id: install

      - name: 'Helm Deploy'
        run: |
          helm repo add envelope-game https://liatrio.github.io/envelope-game
          helm repo update
          helm upgrade --install envelope-game envelope-game/envelope-game --set image.name=${{ env.IMAGE_NAME }}:${{ needs.docker.outputs.tag }} -n ${{ env.NAMESPACE }}
